---
title: 'Resources'
---

* RStudio IDE
    + Download and install [RStudio Desktop](http://www.rstudio.com/products/rstudio/)
    + Download and install [R](http://cran.us.r-project.org/)
* Learn more about [R Markdown](http://rmarkdown.rstudio.com/)
* Packages you should install: `mosaic`, `knitr`, `markdown`
+ [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/):
    + [RStudio IDE](http://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)
    + [R Markdown](http://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
    + [Data Wrangling](http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf) 
    + [Data Visualization](http://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf)

    
    
* Using `R` with the `mosaic` package 
    + the `mosaic` [package](http://cran.r-project.org/web/packages/mosaic/index.html)
    + [Minimal R](http://cran.r-project.org/web/packages/mosaic/vignettes/MinimalR.pdf) for Intro Stats: one page handout with R commands
    + [Resources Related to the mosaic Package](https://cran.r-project.org/web/packages/mosaic/vignettes/mosaic-resources.html): a longer illustrated guide to using `mosaic`
    + [Randomization-based inference using the mosaic package](http://cran.r-project.org/web/packages/mosaic/vignettes/Resampling.pdf)    
    + Nick Horton's videos [introducing RStudio at Amherst](http://www3.amherst.edu/~nhorton/rstudio/)
    + Interactive tutorials via [swirl](http://swirlstats.com/students.html), [DataCamp](https://www.datacamp.com/datafest)
    + Search StackOverflow for the [`r-mosaic` tag](http://stackoverflow.com/questions/tagged/r-mosaic)


* Using `ggplot2`
    + Visit the [website](http://ggplot2.org/)
    + Consult the [documentation](http://docs.ggplot2.org/current/index.html)
    + Read the [book](http://ggplot2.org/book/)
* Using `R` with the `dplyr` [package](http://cran.r-project.org/web/packages/dplyr/index.html)
    + Search StackOverflow for the [`ggplot2` tag](http://stackoverflow.com/questions/tagged/ggplot2)
    + Read the vignettes
* Books
    + *[The Visual Display of Quantitative Information](http://www.edwardtufte.com/tufte/books_vdqi)*, Edward Tufte, Graphics Press, 2001. Hardcover is $27-40.
    + *[Modern Data Science with R](https://www.crcpress.com/Modern-Data-Science-with-R/Baumer-Horton-Kaplan/9781498724487)*, Baumer, Horton and Kaplan.
    

